### ISSUE TITLE
Add "else if" to language

### ISSUE THREAD

**Issue by cstlee** [salesforce/runway-compiler#14]
It would be great if the language supported `else if` in order to avoid excessive indentation and curly-braces.  For instance, the following code

```
if alpha {
    // ...
} else {
    if beta {
        // ...
    }
}
```

can be collapsed into

```
if alpha {
    // ...
} else if beta {
    // ...
}
```

with the introduction of `else if`.  This would especially helpful for readability when writing `if` ladders like the following.

```
if !isReady{
    // get ready
} else if !isOnMark {
    // get on your mark
} else if !isSet {
    // get set
} else {
    // GO!!!
}
```

**Comment by ongardie-sfdc** [comment]
The issue title convinced me. I agree entirely. I think this can be done entirely within the parser, so the rest of the compiler doesn't have to know about it.

**Comment by cstlee** [comment]
Any preference in terms of the token itself?  Some options might include`else if`, `elseif`, and `elif`.

**Comment by ongardie-sfdc** [comment]
I vote for allowing `else if`, since those are already keywords that people might try to use.

I'm ok with additionally allowing `elif` (it's used in Python, at least).

Are there other major languages that use `elseif`? PHP doesn't count.

**Comment by cstlee** [comment]
Do we dislike `elseif` enough to write code to explicitly disallow it?

The current implementation of the parser seems to ignore whitespace when parsing keywords.  This means that two concatenated keywords _without_ whitespace can still match as two separate keywords; both `else if` and `elseif` match without error when the parser expects an `else` followed by an `if`.
